Models/Sede.cs
namespace Fodun.Models{
    public class Sede{
        public int SedeId {get; set;}
        public string Nombre {get; set;}
        public string Tipo {get; set;}
        public string Ubicacion {get; set;}
        public int CapacidadTotal {get; set;}
        public string Descripcion {get; set;}
        public string Imagen {get; set;}
    }
}

Controllers/SedesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;

using Fodun.Data;
using Fodun.Models;

namespace Fodun.Controllers{
   
    public class SedesController : Controller{
        public readonly ReservasContext _context;

        public SedesController(ReservasContext context){
            _context = context;
        }

        public async Task<IActionResult> Index(){
            return View(await _context.Sedes.ToListAsync());
        }

        public async Task<IActionResult> Detalles(int? Id)
        {       
            return View(await _context.Sedes.FirstOrDefaultAsync(s => s.SedeId == Id));  
        }

        public async Task<IActionResult> InicioLogin(){
            return View(await _context.Sedes.ToListAsync());
        }

        public async Task<IActionResult> ListarReservas(){
            return View(await _context.Reservas.ToListAsync());
        }


    }

}

Views/Sedes/Detalles.cshtml
@model Fodun.Models.Sede
@using System.Security.Claims;


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="~/css/site.css">
    <style>
        /* SCROLLBAR */
        .description-column {
            max-height: 300px; /* Define la altura máxima de la columna */
            overflow-y: scroll; /* Activa el scroll vertical */
        }

        /* Opciones del nav */
        .option-btn{
            color: black;
            background-color: white;
            background-color: #ced4da;
            border: none;
            cursor: pointer;
        }
        .option-btn:focus, 
        .option-btn:hover {
            color: black;
            background-color: white;
        }

        .opcionInicio{
            color: #4c5053;
            background-color: white;
            border: none;
            cursor: pointer;
        }

        .opcionInicio:focus, 
        .opcionInicio:hover {
            color: white;
            background-color: #bf2f37;
        }


        .labelIngreso{
            font-size: 12px;
        }
       
        /* Footer al final */
        footer {
            background-color: #bf2f37;
            color: white;
            text-align: center;
            font-family: Arial, sans-serif;
            position: relative;
            width: 100%;
            bottom: 0;
        }

    </style>
<body>
    <div class="content">

       <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <!-- Contenido -->
            </div>
        </nav>
    
           <div class="container-fluid" style="background-color: #ced4da; width: 100vw; margin: 0px; padding: 0px; margin-left: 0px;">           
              <ul class="navega d-flex" style="list-style: none;;">
                <li  class="me-3 "><a asp-controller="Sedes" asp-action="InicioLogin" style=" text-decoration: none;"  class="btn-dark option-btn listOption">Sedes Recreativas y Apartamentos</a></li>
                <li  class="me-3 listOption"><a asp-controller="Sedes" asp-action="ListarReservas" style=" text-decoration: none;"  class="btn-dark option-btn listOption">Mis Reservas</a></li>
                <li class="me-3 listOption"><a style=" text-decoration: none;"  class="btn-dark option-btn listOption">Actualizar Datos</a></li>
                <li class="me-3 listOption"><a asp-controller="Account" asp-action="LogOut" style=" text-decoration: none;"  class="btn-dark option-btn listOption">Cerrar Cesión</a></li>
                <li class="me-5 listOption" style="margin-left: 200px;"><a style=" text-decoration: none;"  class="btn-dark option-btn listOption">
                    @if(User.Identity!.IsAuthenticated){
                    @* Llamar el Claims que antes habia definido dentro de ClaimTypes, que fue el nombre en la función LogIn y devolverlo con Select *@
                    <p style="font-size:16px; width:200px"><i class="bi bi-person-square"></i> Bienvenido, @User.Claims.Where(c => c.Type == ClaimTypes.Name).Select(c => c.Value).SingleOrDefault()
                    </p>
                    }
                </li></a>
              </ul>
        </div>

        <div class="titulo mt-3" style="margin:0px 90px 0px 100px;">
            <h4 class="text-start" style="color: #bf2f37;">Sedes Recreativas y Apartamentos</h4>
        </div>

        <div class="container mt-4">
            <div>
                <button class="opcionInicio">Sedes Recreativas y Apartamentos</button>
                <button class="opcionInicio" style="color: white; background-color: #bf2f37;">Seleccione sus Fechas</button>
            </div>
            <div class="" style="background-color: #bf2f37; height: 5px;" ></div>
            <div class="container-fluid" style="background-color: #e5e7e9;  padding: 20px 20px 10px 20px; ">
                <div class="row">
                    <!-- Columna de datos -->
                    <div class="col-md-4 mt-4">
                        <h5 style="color: #bf2f37;">Mis Fechas</h5>
                        <div class="">                       
                            <form class="mt-3">
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Fecha de Llegada:</label>
                                    <input type="date" class="form-control" id="" style="width: 150px; height: 20px; border-radius: 0px;">
                                </div>
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Fecha de Salida:</label>
                                    <input type="date" class="form-control" id="" style="width: 150px; height: 20px; border-radius: 0px;">

                                </div>
                               
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Noches:</label>
                                    <input type="number" class="form-control" id="" style="width: 90px; height: 20px; border-radius: 0px;">

                                </div>
                                
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Personas:</label>
                                    <input type="number" class="form-control" id="" style="width: 90px; height: 20px; border-radius: 0px;">

                                </div>
                                <div class="mb-3 form-check flex justify-content-end ms-5">
                                    <input type="checkbox" class="form-check-input " id="">
                                    <label class="form-check-label labelIngreso fw-medium" for="exampleCheck1">Servicio de lavanderia:</label>
                                </div>
                                <h5 style="color: #bf2f37;">Total Reserva</h5>
                                
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Habitaciones:</label>
                                    <input type="number" class="form-control" id="" style="width: 90px; height: 20px; border-radius: 0px;">
                                </div>
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Días Ordinarios:</label>
                                    <input type="number" class="form-control" id="" style="width: 90px; height: 20px; border-radius: 0px;">
                                    <input type="number" class="form-control" id="" style="width: 150px; height: 20px; border-radius: 0px;">
                                </div>
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Días Especiales:</label>
                                    <input type="number" class="form-control" id="" style="width: 90px; height: 20px; border-radius: 0px;">
                                    <input type="number" class="form-control" id="" style="width: 150px; height: 20px; border-radius: 0px;">
                                </div>
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Lavandería:</label>
                                    <input type="" class="form-control" id="" style="width: 150px; height: 20px; border-radius: 0px;">
                                </div>
                                <div class="mb-3 d-flex justify-content-center">
                                    <label for="" class="labelIngreso form-label fw-medium me-1">Valor Total:</label>
                                    <h5 style="color: #bf2f37;">$000.000</h5>
                                </div>
                                <div class="mb-3 d-flex justify-content-center">
                                    <button type="submit" class="btn" style="background-color:#bf2f37; color: white; border-radius: 0px;">Seleccionar</button>
                                </div>                                    
                            </form>                        
                        </div>
                        
                    </div>
        
                    <!-- Columna de imágenes -->
                    <div class="col-md-4 mt-4">
                        <h5 style="color: #bf2f37;">@Model.Nombre</h5>
                        <div class="d-flex justify-content-center align-items-center">
                            <img src="@Model.Imagen" alt="" style="width: 300px;">
                        </div>
                        <div class="mt-2 d-flex justify-content-center align-items-center">
                            <div class="row me-1">
                                <img src="@Model.Imagen" alt="" style="width: 80px; height: 50px;">
                            </div>
                            <div class="row me-1">
                                <img src="@Model.Imagen" alt="" style="width: 80px; height: 50px;">
                            </div>
                            <div class="row me-1">
                                <img src="@Model.Imagen" alt="" style="width: 80px; height: 50px;">
                            </div>
                            <div class="row me-1">
                                <img src="@Model.Imagen" alt="" style="width: 80px; height: 50px;">
                            </div>
                        </div>
                        <div class="d-flex justify-content-center align-items-center mt-5">
                            <img src="/img/Mapa.png" alt="" style="width: 80px; height: 50px;">
                            <p class="labelIngreso fw-medium  ms-1" style="color: #bf2f37;">Descargar ruta de llegada</p>
                        </div>
                    </div>
        
                    <!-- Columna de descripción con scroll -->
                    <div class="col-md-4 description-column mt-5" style="height: 700px;">
                        <p>@Model.Descripcion</p>
                        
                    </div>
                </div>
                <div class="row mt-4">
                    <h5 class="fw-medium" style="color: #bf2f37;">Habitaciones/Alojamientos</h5>
                    <table class="table table-striped mt-2">
                        <thead class="table-light" >
                          <tr>
                            <th scope="col">Detalles</th>
                            <th scope="col">Habitacion/Alojamiento</th>
                            <th scope="col">Capacidad</th>
                            <th scope="col">Tarifa día Ordinario</th>
                            <th scope="col">Tarifa día Ordinario</th>
                            <th scope="col">Disponibilidad Fecha Seleccionada</th>
                            <th scope="col">Ver Calendario Disponible</th>
                            <th scope="col">Reservar</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td><i class="bi bi-search"></i></td>
                            <td>1</td>
                            <td>4</td>
                            <td>100.000/td>
                            <td>120.000</td>
                            <td>6</P></td>
                            <td><input type="date" style="width: 30px;"></td>
                            <td><button style="width: 20px; height: 20px;"></button></td>
                          </tr>
                          <tr>
                            <td><i class="bi bi-search"></i></td>
                            <td>1</td>
                            <td>4</td>
                            <td>100.000/td>
                            <td>120.000</td>
                            <td>6</P></td>
                            <td><input type="date" style="width: 30px;"></td>
                            <td><button style="width: 20px; height: 20px;"></button></td>

                            
                          </tr>
                         
                        </tbody>
                </table>
                </div>
            </div>
            
        </div>
    </div>
        

    
    <footer class="bg-body-tertiary mt-4">
        <div class="d-flex justify-content-center align-items-center p-2" style="background-color: #bf2f37;" id="footerContainer">          
            <p class="text-center text-white mb-0">FODUN - Fondo de Docentes Universidad Nacional - Derechos Reservados 
                <i class="bi bi-c-circle"></i> 2014 - Desarrollo por marketingSolutions S.A.S
            </p>          
        </div>
    </footer>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

Views/Sedes/Index.cshtml
@model List<Fodun.Models.Sede>

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <style>

        /* Opciones del nav */
        .option-btn {
            color: black;
            background-color: white;
            background-color: #ced4da;
            border: none;
            cursor: pointer;
        }
        .option-btn:focus, 
        .option-btn:hover {
            color: black;
            background-color: white;
        }

        .opcionInicio{
            color: #4c5053;
            background-color: white;
            border: none;
            cursor: pointer;
        }

        .opcionInicio:focus, 
        .opcionInicio:hover {
            color: white;
            background-color: #bf2f37;
        }

       
        /* Footer al final */
        footer {
            background-color: #bf2f37;
            color: white;
            text-align: center;
            font-family: Arial, sans-serif;
            position: relative;
            width: 100%;
            bottom: 0;
        }

    </style>
<body>
    <div class="content">
            <nav class="navbar bg-body-tertiary">
                <div class="container-fluid">
                    <!-- Contenido -->
                </div>
            </nav>
    
              <div class="container-fluid" style="background-color: #ced4da; width: 100vw; margin: 0px; padding: 0px; margin-left: 0px;">           
              <ul class="navega d-flex" style="list-style: none;;">
                <li class="me-3 "><a asp-action="Index" asp-controller="Sedes" style=" text-decoration: none;" class="btn-dark option-btn listOption">Sedes Recreativas y Apartamentos</a></li>
                <li class="me-3 listOption"><a asp-action="Login" asp-controller="Account" style=" text-decoration: none;" class="btn-dark option-btn listOption">Ingreso y registro</a></li>
              </ul>
        </div>

        <div class="titulo mt-3" style="margin:0px 90px 0px 250px;">
            <h4 class="text-start" style="color: #bf2f37;">Sedes Recreativas y Apartamentos</h4>
        </div>

        <div class="container mt-4">
            <div>
                <button class="opcionInicio" style="color: white; background-color: #bf2f37;">Sedes Recreativas y Apartamentos</button>
                <button class="opcionInicio">Seleccione sus Fechas</button>
            </div>
            <div class="" style="background-color: #bf2f37; height: 5px;" ></div>
            <div class="container-fluid" style="background-color: #e5e7e9; padding: 20px 20px 10px 20px;">
                <div class="">
                    <table class="table table-striped">
                            <thead class="table-light" >
                              <tr>
                                <th scope="col">img</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Descripción</th>
                                <th scope="col">Tipo</th>
                                <th scope="col">Ubicación</th>
                                <th scope="col">Seleccionar</th>
                              </tr>
                            </thead>
                            <tbody>
                            @foreach (var sede in Model){

                              <tr>
                                <td><img src="@Url.Content(@sede.Imagen)" alt="Imagen de @sede.Nombre" style="width: 150px;"></td>
                                <td>@sede.Nombre</td>
                                <td>@sede.Descripcion</td>
                                <td>@sede.Tipo</td>
                                <td>@sede.Ubicacion</td>
                                <td><a asp-controller="Sedes" asp-action="Detalles" asp-route-Id="@sede.SedeId" class="btn" style="background-color:#bf2f37; color: white; border-radius: 0px;">Seleccionar</a></td>
                              </tr>
                              
                             }
                            </tbody>
                      </table>
                </div>
            </div>
            
        </div>
    </div>
        

    
    <footer class="bg-body-tertiary mt-4">
        <div class="d-flex justify-content-center align-items-center p-2" style="background-color: #bf2f37;" id="footerContainer">          
            <p class="text-center text-white mb-0">FODUN - Fondo de Docentes Universidad Nacional - Derechos Reservados 
                <i class="bi bi-c-circle"></i> 2014 - Desarrollo por marketingSolutions S.A.S
            </p>          
        </div>
    </footer>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

Views/Sedes/InicioLogin.cshtml
@model List<Fodun.Models.Sede>
@using System.Security.Claims;
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <style>

        /* Opciones del nav */
        .option-btn {
            color: black;
            background-color: white;
            background-color: #ced4da;
            border: none;
            cursor: pointer;
        }
        .option-btn:focus, 
        .option-btn:hover {
            color: black;
            background-color: white;
        }

        .opcionInicio{
            color: #4c5053;
            background-color: white;
            border: none;
            cursor: pointer;
        }

        .opcionInicio:focus, 
        .opcionInicio:hover {
            color: white;
            background-color: #bf2f37;
        }

       
        /* Footer al final */
        footer {
            background-color: #bf2f37;
            color: white;
            text-align: center;
            font-family: Arial, sans-serif;
            position: relative;
            width: 100%;
            bottom: 0;
        }

    </style>
<body>
    <div class="content">
            <nav class="navbar bg-body-tertiary">
                <div class="container-fluid">
                    <!-- Contenido -->
                </div>
            </nav>
    
           <div class="container-fluid" style="background-color: #ced4da; width: 100vw; margin: 0px; padding: 0px; margin-left: 0px;">           
              <ul class="navega d-flex" style="list-style: none;;">
                <li  class="me-3 "><a asp-controller="Sedes" asp-action="InicioLogin" style=" text-decoration: none;"  class="btn-dark option-btn listOption">Sedes Recreativas y Apartamentos</a></li>
                <li  class="me-3 listOption"><a asp-controller="Sedes" asp-action="ListarReservas" style=" text-decoration: none;"  class="btn-dark option-btn listOption">Mis Reservas</a></li>
                <li class="me-3 listOption"><a style=" text-decoration: none;"  class="btn-dark option-btn listOption">Actualizar Datos</a></li>
                <li class="me-3 listOption"><a asp-controller="Account" asp-action="LogOut" style=" text-decoration: none;"  class="btn-dark option-btn listOption">Cerrar Cesión</a></li>
                <li class="me-5 listOption" style="margin-left: 200px;"><a style=" text-decoration: none;"  class="btn-dark option-btn listOption">
                    @if(User.Identity!.IsAuthenticated){
                    @* Llamar el Claims que antes habia definido dentro de ClaimTypes, que fue el nombre en la función LogIn y devolverlo con Select *@
                    <p style="font-size:16px; width:200px"><i class="bi bi-person-square"></i> Bienvenido, @User.Claims.Where(c => c.Type == ClaimTypes.Name).Select(c => c.Value).SingleOrDefault()
                    </p>
                    }
                </li></a>
              </ul>
        </div>

        <div class="titulo mt-3" style="margin:0px 90px 0px 250px;">
            <h4 class="text-start" style="color: #bf2f37;">Sedes Recreativas y Apartamentos</h4>
        </div>

        <div class="container mt-4">
            <div>
                <button class="opcionInicio" style="color: white; background-color: #bf2f37;">Sedes Recreativas y Apartamentos</button>
                <button class="opcionInicio">Seleccione sus Fechas</button>
            </div>
            <div class="" style="background-color: #bf2f37; height: 5px;" ></div>
            <div class="container-fluid" style="background-color: #e5e7e9; padding: 20px 20px 10px 20px;">
                <div class="">
                    <table class="table table-striped">
                            <thead class="table-light" >
                              <tr>
                                <th scope="col">img</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Descripción</th>
                                <th scope="col">Tipo</th>
                                <th scope="col">Ubicación</th>
                                <th scope="col">Seleccionar</th>
                              </tr>
                            </thead>
                            <tbody>
                            @foreach (var sede in Model){

                              <tr>
                                <td><img src="@Url.Content(@sede.Imagen)" alt="Imagen de @sede.Nombre" style="width: 150px;"></td>
                                <td>@sede.Nombre</td>
                                <td>@sede.Descripcion</td>
                                <td>@sede.Tipo</td>
                                <td>@sede.Ubicacion</td>
                                <td><a asp-controller="Sedes" asp-action="Detalles" asp-route-Id="@sede.SedeId" class="btn" style="background-color:#bf2f37; color: white; border-radius: 0px;">Seleccionar</a></td>
                              </tr>
                              
                             }
                            </tbody>
                      </table>
                </div>
            </div>
            
        </div>
    </div>
        

    
    <footer class="bg-body-tertiary mt-4">
        <div class="d-flex justify-content-center align-items-center p-2" style="background-color: #bf2f37;" id="footerContainer">          
            <p class="text-center text-white mb-0">FODUN - Fondo de Docentes Universidad Nacional - Derechos Reservados 
                <i class="bi bi-c-circle"></i> 2014 - Desarrollo por marketingSolutions S.A.S
            </p>          
        </div>
    </footer>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>